### ISSUE TITLE
bark on all sides of log

### ISSUE THREAD

**Issue by pvprangergod** [ShaneBeee/GraviTree#4]
hi please make a setting so the plugin works for logs with all sides with bark.

this is needed for me because im using custom world generator plugin (openterraingenerator) with trees that have every type of bark log.

thanks!

**Comment by ShaneBeee** [comment]
Which version of Spigot are you using?

**Comment by pvprangergod** [comment]
paperspigot 1.12.2

**Comment by ShaneBeee** [comment]
> paperspigot 1.12.2

Ill take a look at it when i have some time. As far as i remember, the code never specifically mentioned a log that wasn't all sided.

**Comment by ShaneBeee** [comment]
Okay i did a quick skim thru the code. The code should already work for any log type, Im not entirely sure why its not working for all sided logs. 

I just checked out bStats and apparently 2.0% of people using this plugin are running 1.12.2/legacy version.
That being said, I will not be updating the legacy version anymore. 
![Screen Shot 2019-07-25 at 11 55 01 PM](https://user-images.githubusercontent.com/20008482/61932226-a783b700-af37-11e9-9482-014b57d4c079.png)

I understand this may inconvenience "some" people, but frankly 1.12.2 is 2 major versions behind, and was succeeded by 1.13 about a year ago now.

I recommend updating your server to get continued support with plugins.
